### ISSUE TITLE
epkg doesn't know about jsonrpc.el

### ISSUE THREAD

**Issue by jabranham** [emacscollective/epkg#19]
`epkg-update` then `epkg-list-packages` doesn't know about jsonrpc (https://elpa.gnu.org/packages/jsonrpc.html)

Also `epkg-describe-package` eglot doesn't list jsonrpc as a dependency

Note that jsonrpc and json-rpc are different and epkg knows about json-rpc.

**Comment by tarsius** [comment]
`jsonrpc` was one of the four packages that were "on hold", meaning I am aware of it but haven't added it because it is a special snowflake.

`jsonrpc` is a [`:core`](http://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/externals-list) package in GNU Elpa, meaning that it is also part of Emacs itself. Normally that is not a problem because I don't have to mirror such packages -- they are already part of Emacs. The problem here is that `jsonrpc` is not part of the latest Emacs *release*.

I have now add `jsonrpc` as a `file` package, meaning I occupationally import whatever version is currently available at https://git.savannah.gnu.org/cgit/emacs.git/plain/lisp/jsonrpc.el using "update" as the commit message.

Once Emacs 27.1 has been released, I will remove `jsonrpc` and everything is good and civilized again.
