### ISSUE TITLE
Is it possible to search unpackaged files from emacsmirror/emacswiki.org? 

### ISSUE THREAD

**Issue by caadar** [emacscollective/epkg#6]
Say, file `trash-settings.el` exist in the repo. But how to find it?

**Comment by tarsius** [comment]
The database contains information about the *features* provided by a package. That's approximately equivalent to a list of elisp files. It's not exactly the same because the list of features contains no entries for files that do not provide a feature.

So you can use `(epkg-provided 'trash-settings)`. In this case you get back `nil`, so it appears that no package provides that feature. If a package did, then you would get back the package name, a string.

**Comment by caadar** [comment]
Well, so it's a pity that some EmacsWiki files are out from the epkgs system.

**Comment by tarsius** [comment]
https://github.com/melpa/melpa/issues/2342 discusses why packages from the wiki should be avoided.

So if you find a package on the wiki that you would like to use you should contact the author and encourage them to move it to a git or hg repository and to add it to Melpa. Packages that are added to Melpa are also added to the Emacsmirror with a short delay.

**Comment by caadar** [comment]
OK, I see. Thanks!
